//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtleEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string username { get; set; }
        public string pass { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<int> sdt { get; set; }
        public string addr { get; set; }
        public string levelStudy { get; set; }
    }
}
