//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtleEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int stt { get; set; }
        public string email { get; set; }
        public string topic { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateComment { get; set; }
        public Nullable<bool> statusCmt { get; set; }
    
        public virtual CommentTopic CommentTopic { get; set; }
    }
}
