//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtleEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int id { get; set; }
        public string word { get; set; }
        public string mean { get; set; }
        public string typeWord { get; set; }
        public string levelStudy { get; set; }
        public string imgURL { get; set; }
        public string soundURL { get; set; }
    }
}
